<?php

/**
 * @file
 * The Global Redirect module redirects for all paths which have aliases but
 * are not using the aliases which reduces the risk of duplicate content.
 */

/**
 * Implements hook_help().
 */
function globalredirect_help($path, $arg) {
  switch ($path) {
    case 'admin/help#globalredirect':
      return t('This module will do a 301 redirect for all nodes which have an alias but are not using that alias.');
  }
}

/**
 * Implements hook_menu().
 */
function globalredirect_menu() {
  return array(
    'settings' => array(
      'title' => 'Global Redirect',
      'description' => 'Chose which features you would like enabled for Global Redirect',
      'route_name' => 'globalredirect_settings',
    ),
  );
}
